# bootstrap 4 config
baseurl = "https://ethannote.github.io/diary/"
languageCode = "en-us"
title = "Diary"
theme = "hugo-theme-bootstrap4-blog"
paginate = 5

# Theme variables
#
[params]
  # Site author
  author = "EthanNote"

  # Description/subtitle for homepage (can be Markdown)
  description = "Let's remember how busy you were."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    # twitter = "username"
    github = "EthanNote"





# Heather config
# baseurl = "/research_note/"
# languageCode = "en-us"
# title = "Research Note"
# theme = "heather-hugo"

# angels ladder config
#baseurl = "/research_note/"
#languageCode = "zh-cn"
#title = "Research Note"
#theme = "angels-ladder"
#disqusShortname = "EthanNote"

#[Params]
#subtitle = "Life is short, use Python!"
## facebook = "https://facebook.com/foobar"
## twitter = "https://twitter.com/foobar"
#github = "https://github.com/EthanNote"
#showsRSS = true
#profile = "/images/profile.png"
#copyright = "Written by EthanNote"
## analytics = "UA-XXXXXXXX-X"
## shareThis = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"


# paper now config
# baseurl         = "https://ethannote.github.io/research_note/"
#theme           = "hugo-paper-now"
#languageCode    = "en-us"
#title           = "Site Title | Research Note"
#canonifyurls    = true
